### ISSUE TITLE
Name of the `envlist` / `env_list` section

### ISSUE THREAD

**Issue by eumiro** [tox-dev/tox-ini-fmt#160]
According to https://tox.wiki/en/latest/config.html#env_list both `envlist` and `env_list` are possible.

When running the latest version of `tox-ini-fmt` within `pre-commit`, it rejects `envlist` and suggests `env_list`. This conflicts with `check-python-versions` that cannot read `env_list` and expects `envlist`. As result, I cannot write single name of the section to satisfy both plugins.

To be fair, I am writing this issue to both projects (https://github.com/mgedmin/check-python-versions/issues/42), but it would be nice if both alternatives were accepted. Would you like a PR?

**Comment by gaborbernat** [comment]
The new suggested format is the only one supported. Truly. The other one is considered deprecated, but we keep it around for backwards compatibility.

**Comment by eumiro** [comment]
Thank you. Looks like a good suggestion to fix `check-python-versions`.
