### ISSUE TITLE
Conditional dependencies are mangled

### ISSUE THREAD

**Issue by Julian** [tox-dev/tox-ini-fmt#21]
`git clone https://github.com/Julian/regret && cd regret && tox-ini-fmt tox.ini` turns (subset of tox.ini shown):

```
deps =
    -r{toxinidir}/test-requirements.txt
    virtue

    codecov,coverage: coverage
    codecov: codecov
```

into

```
deps =
  -r{toxinidir}/test-requirements.txt
  codecov,coverage:
  codecov:
  virtue
```

(where the conditional dependencies are gone)

**Comment by gaborbernat** [comment]
Yeah conditionals are not supported yet for dependencies. In my projects I don't use them 😂

**Comment by gaborbernat** [comment]
This should now work with https://pypi.org/project/tox-ini-fmt/0.4.0/
