### ISSUE TITLE
Ordering of envvars

### ISSUE THREAD

**Issue by Julian** [tox-dev/tox-ini-fmt#22]
(I forget whether the below is true, if not obviously feel free to close)

`git clone https://github.com/Julian/regret && cd regret && tox-ini-fmt tox.ini`

turns

```
setenv =
    {[testenv]setenv}
    COVERAGE_DEBUG_FILE={envtmpdir}/coverage-debug
    COVERAGE_FILE={envtmpdir}/coverage-data
```

into

```
setenv =
  COVERAGE_DEBUG_FILE = {envtmpdir}/coverage-debug
  COVERAGE_FILE = {envtmpdir}/coverage-data
  {[testenv]setenv = {[testenv]setenv}
```

is that a safe change?

What if the parent `setenv` contained those envvars? Presumably those are processed in order right, and the original way, the overridden values win, whereas after sorting, the parent values will win?

(Again if that's false feel free to close :)

**Comment by gaborbernat** [comment]
The order does not matter. In old pip it might... But with pip having a resolver it's irrelevant.

**Comment by gaborbernat** [comment]
If you're relying on ordering of these you're doing something wrong 🤔I feel like .

**Comment by Julian** [comment]
I'm talking about tox, not pip, and how tox decides to break ties in sections.

**Comment by gaborbernat** [comment]
I still stand by of if you're relying on ordering of these you're doing something wrong 🤔I feel like .

**Comment by Julian** [comment]
I don't know of any other solution really. tox's configuration format only has this, so if you want a default value and to override it in some testenvs I don't think you really have another choice. You could give up on sharing between sections entirely I guess. Maybe that's indeed the thing to do in that situation.

**Comment by gaborbernat** [comment]
I mean we can swap it to the beginning always 🤠 to support override.

**Comment by Julian** [comment]
Yeah that maybe was what I was thinking
