### ISSUE TITLE
One-line sections become multiline

### ISSUE THREAD

**Issue by Julian** [tox-dev/tox-ini-fmt#23]
(Again not sure if this is intentional, feel free to close if so!)

`git clone https://github.com/Julian/regret && cd regret && tox-ini-fmt tox.ini`

turns

```
[testenv:build]
deps = build
commands = {envpython} -m build {toxinidir} --outdir {envtmpdir}/dist
```

into

```

[testenv:build]
deps =
    build
commands =
    {envpython} -m build {toxinidir} --outdir {envtmpdir}/dist
```

The README says "values that contain a list are split one value per line (PR/merge friendly)" which makes a lot of sense of course, but for some envs they'll never have more than one dep or command by their nature. If not by default, maybe at least an option to keep `len == 1` things on one line?

**Comment by gaborbernat** [comment]
This is by design. Sections that can become multiline are always formatted multiline so that they're merge friendly.

**Comment by gaborbernat** [comment]
> If not by default, maybe at least an option to keep `len == 1` things on one line?

I'm not to keen to add to many config knobs on this, want it to be like black. But let's say I'd consider adding a knob for this.
