### ISSUE TITLE
Trailing zeros are stripped from versions

### ISSUE THREAD

**Issue by Julian** [tox-dev/tox-ini-fmt#24]
Versions in e.g. dependencies like `1.2.0` are emitted as `1.2`.

This is theoretically equivalent when using "=", but not when using other specifiers. E.g.:

```
⊙  tox-ini-fmt =(echo '                                                                                                                                                                         julian@Air ●
[testenv]
deps =
  foo~=1.0.0
')
```

emits

```
--- /tmp/zshXDAZNW

+++ /tmp/zshXDAZNW

@@ -1,5 +1,3 @@

-
 [testenv]
 deps =
-  foo~=1.0.0
-
+  foo~~=1
```

where that version specification now has different meaning. (Also it looks like the `~` itself was mangled).

**Comment by gaborbernat** [comment]
Indeed we should only do the striping on equal and greater and equal 🎉
