### ISSUE TITLE
Number of spaces for indentation

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox-ini-fmt#26]
Hi,

I just tried this new tool, and it works great, and I like the output a lot.

I am curious why you decided to go with 2 spaces for indentation.

Pretty much all of my own projects, the projects I contribute to (zope, plone, ...) or I use e.g. tox, pytest, flask, ... use 4 spaces for indentation in config files, especially for `tox.ini`.

As a Python developer, this is something we are used to, but imho the better reason is, that the ini file then is way easier to scan, as there is a bigger distinction between keys and values ( This is similar to when you have a text and you make the heading not just one font size bigger, but some more).

Do you plan to make the number of spaces configurable?

Thanks!

**Comment by gaborbernat** [comment]
I went for the two space to save some screen real estate, that being said this project wants to compliment ``setup-cfg-fmt``, and that uses 4 spaces, so we should probably also use 4 spaces, now that I think about it.

**Comment by jugmac00** [comment]
Great news!

Well, I spent some time on my smartphone reading the source how to figure out how to implement a command line flag to make this optional, but just using indentation of 4 would be even better :-)

Just in case, I create #28 - no pressure :-)
