### ISSUE TITLE
logic for application of line breaks?

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox-ini-fmt#27]
Hi,

I just tried this tool ( https://github.com/jugmac00/hibpcli/pull/51/files ) and I do not see a rule yet, when line breaks are applied and when not.

e.g. after `develop =` there is a line break and `true` is on the next line, but there is `skip_install = true`. There are also line breaks after `deps =` and `commands`.

Also, the configuration sections for `flake8` and `isort` were not touched at all.

**Update**
Ok, I stepped through the code and now I know why the `flake8` and `isort` sections did not get touched :+1: 

https://github.com/tox-dev/tox-ini-fmt/blob/02157381bcde2340617efc6b5995b841d6caff03/src/tox_ini_fmt/formatter/__init__.py#L10-L22

You do not generically sort and format all sections, but currently only the `tox` and `testenv(s)` sections.

**Update 2**
`develop` is a typo (in my config) and should read `usedevelop` 😬 I start to see the pattern 😁

**Update 3**
I think it would be a good idea to update the readme that other sections besides `tox` and `testenv` won't be touched.

**Comment by gaborbernat** [comment]
> I think it would be a good idea to update the readme that other sections besides `tox` and `testenv` won't be touched.

For now yes. 

As far as sorting flake8, pytest, isort, pylint and etcetera sections I'm open to it. But they would be new features. So if you'd like to see that happen open a feature issue request, please 😊 

![thanks](https://media.tenor.co/images/7366ae69129776ba7660cd8e981460de/tenor.gif)

**Comment by jugmac00** [comment]
Oh ... you are faster in creating issues and PRs than I can type :-)
