### ISSUE TITLE
isort support

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox-ini-fmt#33]
Add support for formatting isort sections.

**Comment by jugmac00** [comment]
All possible **isort** settings... 😮
https://github.com/PyCQA/isort/wiki/isort-Settings

**Comment by gaborbernat** [comment]
We don't have to support all out of box 🤔 maybe a few common ones just first and iterate on it.

**Comment by gaborbernat** [comment]
These nowadays should live within pyproject.toml so this will be a won't do.
